# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2025.1.3
_src_path: gh:softboiler/copier-pipeline
actions_runner: ubuntu-24.04
github_repo_name: amsl-labjack
package_name: amsl_labjack
project_description: LabJack utilities for AMSL lab
project_email: blake.naccarato@gmail.com
project_name: amsl-labjack
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 2025.0.0
publish_project: false
python_version: '3.11'
year_of_project_creation: 2025
